/**
 * Pure planner for the "Sync agents from Google Sheets" admin feature.
 *
 * Takes raw sheet rows + EventConfig knobs + Pod-Head directory + per-agent
 * DB state, returns a typed `SyncPlan` describing what would be created /
 * updated / skipped on apply. No Prisma imports — unit-testable in isolation.
 *
 * Header detection is regex-based to tolerate the real Google Form export
 * shape: typos (`Pority`, `Preffered`), ordinals (`1st`, `2nd`, `10th`), and
 * duplicate columns (e.g. two `6th Priority Pod`). First column per rank
 * wins; duplicates are surfaced as warnings.
 *
 * The DB bridge (and `db.$transaction` calls) live in the admin action file
 * at `src/app/admin/agent-sync/actions.ts`. Keep that boundary.
 */

import { seededRng } from "./matching/rng";
import {
  nameFromEmail,
  normalizeName as norm,
  splitNameAndEmpId
} from "./sync-helpers";

// Re-export for back-compat with code/tests that imported from this module.
export { nameFromEmail };

/** Sync-issue codes persisted on User.syncIssues. */
export const SYNC_ISSUE_DUPLICATE_POD_HEADS = "DUPLICATE_POD_HEADS";

export type RowOutcome =
  | {
      kind: "create" | "update";
      rowIndex: number;
      email: string;
      name: string;
      pitch: string;
      preferredDomains: string[];
      // Resolved Pod-Head profile IDs in rank order (rank 1 first).
      rankings: string[];
      /** Non-fatal sync issues to persist on User.syncIssues. */
      flags: string[];
    }
  | {
      kind: "skip";
      rowIndex: number;
      email: string | null;
      reason: string;
    };

export interface SyncPlan {
  topN: number;
  outcomes: RowOutcome[];
  /** Header-level warnings (e.g. duplicate priority columns). Surface in UI. */
  warnings: string[];
  summary: {
    rowsTotal: number;
    creates: number;
    updates: number;
    skips: number;
    /** Outcomes flagged with at least one sync issue. */
    duplicates: number;
  };
}

/** Pod-Head record needed for resolution. */
export interface PodHeadDirEntry {
  podHeadProfileId: string;
  name: string;
  email: string;
  /** Stored EMP ID, if any. Used to match priority cells like "Name - 1234". */
  empId: string | null;
}

/** Per-existing-agent state needed to decide create/update/skip. */
export interface ExistingAgent {
  /** lowercased email */
  email: string;
  /** User.role — if not AGENT the row is skipped to avoid corrupting profile data. */
  role: "AGENT" | "POD_HEAD" | "ORCH";
  /** Whether the agent has submitted preferences (FCFS-stamped). */
  preferencesSubmitted: boolean;
  /** Whether the agent has any AgentPodHeadRanking row with autoGenerated=false. */
  hasManualRankings: boolean;
}

export interface PlanInput {
  rows: string[][];
  topN: number;
  allowedEmailDomains: string[];
  podHeads: PodHeadDirEntry[];
  existingAgents: ExistingAgent[];
}

// Single-column resolvers — first match wins.
const RE_EMAIL_ADDRESS = /\bemail\s*address\b/;
const RE_OFFICIAL_EMAIL = /\bofficial\s*email\b/;
const RE_PITCH = /\bquick\s*intro|\bintro\b|\bdescription\b|\bbio\b|\bpitch\b/;

// Multi-column resolvers — pull the rank number out of the header.
// `p\w*ity` matches both "priority" and "pority" (typo in live form).
const RE_PRIORITY_HEADER =
  /^(\d+)(?:st|nd|rd|th)?\s+p\w*ity\s+pod\b/;
// `pre?ff?ered?` matches "preferred" and "preffered" (typo in live form).
const RE_DOMAIN_HEADER =
  /^(\d+)(?:st|nd|rd|th)?\s+pre?ff?ered?\s+domain\b/;

interface HeaderIndex {
  emailAddress: number;
  officialEmail: number;
  pitch: number;
  /** col idx for each rank — rank 1 at index 0, etc. Sparse if config N < some present rank. */
  priorities: number[];
  /** col idx for preferred-domain rank — rank 1 at index 0. May be sparse. */
  domains: number[];
}

interface HeaderResult {
  index: HeaderIndex;
  warnings: string[];
}

function indexHeaders(headerRow: string[], topN: number): HeaderResult {
  const warnings: string[] = [];
  let emailAddress = -1;
  let officialEmail = -1;
  let pitch = -1;
  const priorities: number[] = [];
  const domains: number[] = [];

  for (let i = 0; i < headerRow.length; i++) {
    const h = norm(headerRow[i] ?? "");
    if (!h) continue;

    const prio = h.match(RE_PRIORITY_HEADER);
    if (prio) {
      const r = Number(prio[1]) - 1;
      if (priorities[r] === undefined) priorities[r] = i;
      else warnings.push(`duplicate priority column for rank ${r + 1} (col ${i + 1}); first occurrence kept`);
      continue;
    }
    const dom = h.match(RE_DOMAIN_HEADER);
    if (dom) {
      const r = Number(dom[1]) - 1;
      if (domains[r] === undefined) domains[r] = i;
      else warnings.push(`duplicate preferred-domain column for rank ${r + 1} (col ${i + 1}); first occurrence kept`);
      continue;
    }
    if (officialEmail === -1 && RE_OFFICIAL_EMAIL.test(h)) {
      officialEmail = i;
      continue;
    }
    if (emailAddress === -1 && RE_EMAIL_ADDRESS.test(h)) {
      emailAddress = i;
      continue;
    }
    if (pitch === -1 && RE_PITCH.test(h)) {
      pitch = i;
      continue;
    }
  }

  if (officialEmail === -1 && emailAddress === -1) {
    throw new Error(
      `Missing email column (need "Official Email" or "Email Address").`
    );
  }
  if (pitch === -1) {
    throw new Error(
      `Missing intro/description column (need "Quick Intro of your self" or similar).`
    );
  }
  for (let r = 0; r < topN; r++) {
    if (priorities[r] === undefined) {
      throw new Error(`Missing priority column for rank ${r + 1}.`);
    }
  }

  return {
    index: { emailAddress, officialEmail, pitch, priorities, domains },
    warnings
  };
}

function buildPodHeadByName(
  podHeads: PodHeadDirEntry[]
): Map<string, PodHeadDirEntry[]> {
  const byName = new Map<string, PodHeadDirEntry[]>();
  for (const ph of podHeads) {
    const k = norm(ph.name);
    const arr = byName.get(k) ?? [];
    arr.push(ph);
    byName.set(k, arr);
  }
  return byName;
}


/**
 * Build the typed plan. Pure function — no I/O, deterministic given inputs.
 *
 * Throws on header-level problems (the whole sheet is unusable). Per-row
 * issues become `kind: "skip"` outcomes, so partial sheets still surface a
 * useful report instead of bailing out.
 */
export function planAgentSync(input: PlanInput): SyncPlan {
  const { rows, topN, allowedEmailDomains, podHeads, existingAgents } = input;

  if (rows.length === 0) {
    throw new Error("Sheet is empty.");
  }

  const { index: headers, warnings } = indexHeaders(rows[0], topN);
  const allowedDomains = new Set(allowedEmailDomains.map(norm));
  const podHeadByName = buildPodHeadByName(podHeads);
  const podHeadByEmpId = new Map<string, PodHeadDirEntry>();
  for (const ph of podHeads) {
    if (ph.empId) podHeadByEmpId.set(ph.empId, ph);
  }
  const existingByEmail = new Map(
    existingAgents.map((e) => [norm(e.email), e])
  );

  const outcomes: RowOutcome[] = [];
  const seenEmailsInSheet = new Set<string>();
  let creates = 0;
  let updates = 0;
  let skips = 0;
  let duplicates = 0;

  // For DUPLICATE_POD_HEADS substitution: when the same Pod Head appears
  // twice in one row we keep the earliest occurrence and substitute the
  // later slot with a Pod Head not yet used in this row, picked to balance
  // load at that rank position. Counts are built up across rows in this run.
  const allPodHeadIds = podHeads
    .map((ph) => ph.podHeadProfileId)
    .sort();
  /** rank K (0-indexed) -> Map<podHeadProfileId, count assigned at rank K> */
  const rankCounts = new Map<number, Map<string, number>>();
  const bumpRankCount = (k: number, id: string) => {
    const bucket = rankCounts.get(k) ?? new Map<string, number>();
    bucket.set(id, (bucket.get(id) ?? 0) + 1);
    rankCounts.set(k, bucket);
  };
  const pickSubstitute = (
    k: number,
    excluded: Set<string>,
    email: string
  ): string | null => {
    const candidates = allPodHeadIds.filter((id) => !excluded.has(id));
    if (candidates.length === 0) return null;
    const counts = rankCounts.get(k);
    let minCount = Infinity;
    for (const id of candidates) {
      const c = counts?.get(id) ?? 0;
      if (c < minCount) minCount = c;
    }
    const minSet = candidates.filter(
      (id) => (counts?.get(id) ?? 0) === minCount
    );
    if (minSet.length === 1) return minSet[0];
    const rng = seededRng(`agent-sync-dup-${email}-${k}`);
    return minSet[Math.floor(rng() * minSet.length)];
  };

  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    const rowIndex = i + 1; // 1-based, includes header row

    const cellAt = (idx: number): string =>
      idx >= 0 && idx < row.length ? (row[idx] ?? "") : "";

    const rawOfficial = cellAt(headers.officialEmail).trim();
    const rawAddress = cellAt(headers.emailAddress).trim();
    const rawPitch = cellAt(headers.pitch).trim();
    const priorityCells = headers.priorities.map((idx) => cellAt(idx).trim());
    const domainCells = headers.domains.map((idx) => cellAt(idx).trim());

    // Treat row as a no-op if every meaningful cell is empty (common in
    // Google Sheets API responses with trailing blank rows).
    const allBlank =
      !rawOfficial &&
      !rawAddress &&
      !rawPitch &&
      priorityCells.every((c) => !c);
    if (allBlank) continue;

    // Email resolution: Official Email primary, Email Address fallback.
    const chosenEmail = (rawOfficial || rawAddress).toLowerCase();

    const reject = (reason: string) => {
      outcomes.push({
        kind: "skip",
        rowIndex,
        email: chosenEmail || null,
        reason
      });
      skips++;
    };

    if (!chosenEmail) {
      reject("missing email (both Official Email and Email Address empty)");
      continue;
    }

    const at = chosenEmail.indexOf("@");
    if (at < 1 || at === chosenEmail.length - 1) {
      reject(`invalid email "${chosenEmail}"`);
      continue;
    }
    const domain = chosenEmail.slice(at + 1);
    if (!allowedDomains.has(domain)) {
      reject(`email domain "${domain}" not in allowedEmailDomains`);
      continue;
    }

    if (seenEmailsInSheet.has(chosenEmail)) {
      reject(`duplicate email "${chosenEmail}" within sheet`);
      continue;
    }
    seenEmailsInSheet.add(chosenEmail);

    if (!rawPitch) {
      reject("missing intro/description");
      continue;
    }

    const existing = existingByEmail.get(chosenEmail);
    if (existing && existing.role !== "AGENT") {
      reject(
        `user exists with role ${existing.role}; sync only writes AGENT rows`
      );
      continue;
    }
    if (existing?.preferencesSubmitted) {
      reject(
        "agent already submitted preferences; manual choices preserved"
      );
      continue;
    }
    if (existing?.hasManualRankings) {
      reject(
        "agent has manually-edited rankings; sync skipped to avoid stomping"
      );
      continue;
    }

    // Resolve priority columns → Pod-Head profile IDs.
    // Cell format may be either plain "Hafiz Faraz Ahmed" or "Hafiz Faraz Ahmed - 1676".
    // Try EMP-ID match first (canonical, tolerant of name typos); fall back to name match.
    const rankings: string[] = [];
    const seenPodHeadsInRow = new Set<string>();
    const flags = new Set<string>();
    let rowError: string | null = null;
    for (let k = 0; k < topN; k++) {
      const cell = priorityCells[k];
      if (!cell) {
        rowError = `priority ${k + 1} is empty`;
        break;
      }
      const { name: priorityName, empId: priorityEmpId } =
        splitNameAndEmpId(cell);

      let match: PodHeadDirEntry | undefined;
      if (priorityEmpId) {
        match = podHeadByEmpId.get(priorityEmpId);
      }
      if (!match) {
        const candidates = podHeadByName.get(norm(priorityName));
        if (!candidates || candidates.length === 0) {
          rowError = `priority ${k + 1}: Pod Head "${cell}" not found`;
          break;
        }
        if (candidates.length > 1) {
          rowError = `priority ${k + 1}: Pod Head name "${priorityName}" is ambiguous (${candidates.length} matches)`;
          break;
        }
        match = candidates[0];
      }

      let assignedId: string;
      if (seenPodHeadsInRow.has(match.podHeadProfileId)) {
        flags.add(SYNC_ISSUE_DUPLICATE_POD_HEADS);
        const sub = pickSubstitute(k, seenPodHeadsInRow, chosenEmail);
        if (sub === null) {
          // Every known Pod Head already used in this row. Drop the slot.
          continue;
        }
        assignedId = sub;
      } else {
        assignedId = match.podHeadProfileId;
      }
      seenPodHeadsInRow.add(assignedId);
      rankings.push(assignedId);
      bumpRankCount(k, assignedId);
    }
    if (rowError) {
      reject(rowError);
      continue;
    }

    // Preferred domains — dedupe case-insensitively, preserve order.
    const preferredDomains: string[] = [];
    const seenDomains = new Set<string>();
    for (const cell of domainCells) {
      if (!cell) continue;
      const key = cell.toLowerCase();
      if (seenDomains.has(key)) continue;
      seenDomains.add(key);
      preferredDomains.push(cell);
    }

    const kind: "create" | "update" = existing ? "update" : "create";
    if (kind === "create") creates++;
    else updates++;
    const flagList = Array.from(flags).sort();
    if (flagList.length > 0) duplicates++;

    outcomes.push({
      kind,
      rowIndex,
      email: chosenEmail,
      name: nameFromEmail(chosenEmail),
      pitch: rawPitch,
      preferredDomains,
      rankings,
      flags: flagList
    });
  }

  return {
    topN,
    outcomes,
    warnings,
    summary: {
      rowsTotal: rows.length - 1,
      creates,
      updates,
      skips,
      duplicates
    }
  };
}
