/**
 * Matching service — DB ↔ pure engine bridge (SRS §7).
 *
 * Each `run*` function:
 *   1. Computes auto-fill rows for non-submitters and persists them with
 *      `autoGenerated = true` (idempotent — only fills missing).
 *   2. Builds engine input from the (now-complete) preference tables.
 *   3. Runs the pure matching engine (no Prisma imports leak in).
 *   4. Replaces any prior draft `MatchingRun` of the same type and writes
 *      a new draft with `isFinalized = false`. The full placement map is
 *      stored in `MatchingRun.stats.placements` so finalize doesn't need
 *      to re-run the engine.
 *
 * `finalizeMatch(type)` reads the draft and applies placements to the
 * entity columns inside a single transaction. `rollbackMatch(type)` nulls
 * those columns and marks the run `ROLLED_BACK`.
 *
 * This module IS server-only (touches Prisma). Callers (admin server
 * actions) wrap each function with `requireAdmin()` + `requirePhase()`.
 */

import type { MatchType, Prisma } from "@prisma/client";

import { db } from "@/lib/db";
import { getConfig } from "@/lib/config";
import {
  assignProjects,
  autoFillPreferences,
  completeMatch,
  hospitalResidents,
  type AutoFillInput,
  type HRInput,
  type HRResult,
  type ProjectAssignmentInput
} from "@/lib/matching";

// === Public types ===

export interface RunSummary {
  runId: string;
  type: MatchType;
  isFinalized: boolean;
  stats: {
    totalProposals?: number;
    rounds?: number;
    matchedCount: number;
    rosterSizes: Record<string, number>;
    autoFilledCount: number;
    durationMs: number;
  };
}

export interface MatchingStatus {
  ORCH_PODHEAD: { runId: string | null; isFinalized: boolean; stats: RunSummary["stats"] | null };
  PODHEAD_AGENT: { runId: string | null; isFinalized: boolean; stats: RunSummary["stats"] | null };
  PROJECT_ASSIGNMENT: { runId: string | null; isFinalized: boolean; stats: RunSummary["stats"] | null };
}

// === Internal helpers ===

async function clearDrafts(type: MatchType) {
  await db.matchingRun.deleteMany({
    where: { type, isFinalized: false }
  });
}

async function ensureNotFinalized(type: MatchType) {
  const finalized = await db.matchingRun.findFirst({
    where: { type, isFinalized: true, status: { not: "ROLLED_BACK" } },
    orderBy: { startedAt: "desc" }
  });
  if (finalized) {
    throw new Error(
      `${type} already finalized (run ${finalized.id}). Rollback first to re-run.`
    );
  }
}

async function requirePrerequisite(type: MatchType): Promise<void> {
  if (type === "ORCH_PODHEAD") return;
  const prereq: MatchType = type === "PODHEAD_AGENT" ? "ORCH_PODHEAD" : "PODHEAD_AGENT";
  const finalized = await db.matchingRun.findFirst({
    where: { type: prereq, isFinalized: true, status: "COMPLETED" },
    orderBy: { startedAt: "desc" }
  });
  if (!finalized) {
    throw new Error(`Finalize ${prereq} before running ${type}.`);
  }
}

/**
 * Persist auto-fill rows. For each preference type the engine emits, we
 * skip persisting if the (from,to) already exists — the unique constraint
 * would error otherwise. The fast path: only fill for the users we know
 * haven't submitted.
 */
async function persistAutoFill(
  matchType: MatchType,
  runId: string,
  config: Awaited<ReturnType<typeof getConfig>>
): Promise<{ autoFilledUserIds: string[] }> {
  const [podHeadRows, orchRows, agentRows, projectRows] = await Promise.all([
    db.podHeadProfile.findMany({
      select: {
        id: true,
        userId: true,
        orchRankings: { select: { orchId: true } },
        agentSelections: { select: { agentId: true } },
        projectPicks: { select: { projectId: true } }
      }
    }),
    db.orchProfile.findMany({
      select: {
        id: true,
        userId: true,
        podHeadSelections: { select: { podHeadId: true } }
      }
    }),
    db.agentProfile.findMany({
      select: {
        id: true,
        userId: true,
        podHeadRankings: { select: { podHeadId: true } }
      }
    }),
    db.project.findMany({ select: { id: true } })
  ]);

  const phIds = podHeadRows.map((p) => p.id);
  const orchIds = orchRows.map((o) => o.id);
  const agentIds = agentRows.map((a) => a.id);
  const projectIds = projectRows.map((p) => p.id);

  const podHeadsWhoRankedOrchs = new Set(
    podHeadRows.filter((p) => p.orchRankings.length > 0).map((p) => p.id)
  );
  const orchsWhoSelectedPodHeads = new Set(
    orchRows.filter((o) => o.podHeadSelections.length > 0).map((o) => o.id)
  );
  const podHeadsWhoSelectedAgents = new Set(
    podHeadRows.filter((p) => p.agentSelections.length > 0).map((p) => p.id)
  );
  const agentsWhoRankedPodHeads = new Set(
    agentRows.filter((a) => a.podHeadRankings.length > 0).map((a) => a.id)
  );
  const podHeadsWhoPickedProjects = new Set(
    podHeadRows.filter((p) => p.projectPicks.length > 0).map((p) => p.id)
  );

  const af = autoFillPreferences({
    matchType,
    runId,
    podHeads: phIds,
    orchs: orchIds,
    agents: agentIds,
    projects: projectIds,
    podHeadsWhoRankedOrchs,
    orchsWhoSelectedPodHeads,
    podHeadsWhoSelectedAgents,
    agentsWhoRankedPodHeads,
    podHeadsWhoPickedProjects,
    config: {
      podHeadsPerOrch: config.podHeadsPerOrch,
      agentsPerPodHead: config.agentsPerPodHead,
      agentRanksTopNPodHeads: config.agentRanksTopNPodHeads,
      podHeadRanksTopNAgents: config.podHeadRanksTopNAgents,
      projectsPerPodHead: config.projectsPerPodHead
    }
  } satisfies AutoFillInput);

  // Persist in a transaction. createMany skipDuplicates avoids unique-
  // constraint errors when re-running.
  await db.$transaction([
    db.podHeadOrchRanking.createMany({
      data: af.podHeadOrchRankings.map((r) => ({
        podHeadId: r.fromId,
        orchId: r.toId,
        rank: r.rank,
        autoGenerated: true
      })),
      skipDuplicates: true
    }),
    db.orchPodHeadSelection.createMany({
      data: af.orchPodHeadSelections.map((r) => ({
        orchId: r.fromId,
        podHeadId: r.toId,
        rank: r.rank,
        autoGenerated: true
      })),
      skipDuplicates: true
    }),
    db.podHeadAgentSelection.createMany({
      data: af.podHeadAgentSelections.map((r) => ({
        podHeadId: r.fromId,
        agentId: r.toId,
        rank: r.rank,
        autoGenerated: true
      })),
      skipDuplicates: true
    }),
    db.agentPodHeadRanking.createMany({
      data: af.agentPodHeadRankings.map((r) => ({
        agentId: r.fromId,
        podHeadId: r.toId,
        rank: r.rank,
        autoGenerated: true
      })),
      skipDuplicates: true
    }),
    db.podHeadProjectPick.createMany({
      data: af.podHeadProjectPicks.map((r) => ({
        podHeadId: r.fromId,
        projectId: r.toId,
        rank: r.rank,
        autoGenerated: true
      })),
      skipDuplicates: true
    })
  ]);

  // Map profile ids → user ids for the autoFilledUserIds list
  // (per SRS we record User ids, not profile ids).
  const userIdByProfile = new Map<string, string>();
  for (const p of podHeadRows) userIdByProfile.set(p.id, p.userId);
  for (const o of orchRows) userIdByProfile.set(o.id, o.userId);
  for (const a of agentRows) userIdByProfile.set(a.id, a.userId);

  return {
    autoFilledUserIds: af.autoFilledUserIds
      .map((id) => userIdByProfile.get(id))
      .filter((id): id is string => typeof id === "string")
  };
}

// === Run 1: ORCH_PODHEAD ===

export async function runOrchPodHeadMatch(actorId: string): Promise<RunSummary> {
  const t0 = Date.now();
  await ensureNotFinalized("ORCH_PODHEAD");
  await clearDrafts("ORCH_PODHEAD");

  const config = await getConfig();
  const tempRunId = `temp-${Date.now()}`;

  const { autoFilledUserIds } = await persistAutoFill(
    "ORCH_PODHEAD",
    tempRunId,
    config
  );

  // Build HR input: Pod Heads (residents) propose to Orchs (hospitals).
  const [podHeads, orchs] = await Promise.all([
    db.podHeadProfile.findMany({
      select: {
        id: true,
        orchRankings: {
          orderBy: { rank: "asc" },
          select: { orchId: true }
        }
      }
    }),
    db.orchProfile.findMany({
      select: {
        id: true,
        podHeadSelections: {
          orderBy: { rank: "asc" },
          select: { podHeadId: true }
        }
      }
    })
  ]);

  const hrInput: HRInput = {
    residents: podHeads.map((p) => ({
      id: p.id,
      preferences: p.orchRankings.map((r) => r.orchId)
    })),
    hospitals: orchs.map((o) => ({
      id: o.id,
      capacity: config.podHeadsPerOrch,
      preferences: o.podHeadSelections.map((s) => s.podHeadId)
    }))
  };

  const hr = hospitalResidents(hrInput);
  const completed = completeMatch(hr, hrInput.hospitals);

  return persistDraft({
    type: "ORCH_PODHEAD",
    actorId,
    autoFilledUserIds,
    hrResult: completed,
    placements: completed.matched,
    rosters: completed.rosters,
    durationMs: Date.now() - t0
  });
}

// === Run 2: PODHEAD_AGENT ===

export async function runPodHeadAgentMatch(actorId: string): Promise<RunSummary> {
  const t0 = Date.now();
  await requirePrerequisite("PODHEAD_AGENT");
  await ensureNotFinalized("PODHEAD_AGENT");
  await clearDrafts("PODHEAD_AGENT");

  const config = await getConfig();
  const tempRunId = `temp-${Date.now()}`;

  const { autoFilledUserIds } = await persistAutoFill(
    "PODHEAD_AGENT",
    tempRunId,
    config
  );

  const [agents, podHeads] = await Promise.all([
    db.agentProfile.findMany({
      select: {
        id: true,
        podHeadRankings: {
          orderBy: { rank: "asc" },
          select: { podHeadId: true }
        }
      }
    }),
    db.podHeadProfile.findMany({
      select: {
        id: true,
        agentSelections: {
          orderBy: { rank: "asc" },
          select: { agentId: true }
        }
      }
    })
  ]);

  const hrInput: HRInput = {
    residents: agents.map((a) => ({
      id: a.id,
      preferences: a.podHeadRankings.map((r) => r.podHeadId)
    })),
    hospitals: podHeads.map((p) => ({
      id: p.id,
      capacity: config.agentsPerPodHead,
      preferences: p.agentSelections.map((s) => s.agentId)
    }))
  };

  const hr = hospitalResidents(hrInput);
  const completed = completeMatch(hr, hrInput.hospitals);

  return persistDraft({
    type: "PODHEAD_AGENT",
    actorId,
    autoFilledUserIds,
    hrResult: completed,
    placements: completed.matched,
    rosters: completed.rosters,
    durationMs: Date.now() - t0
  });
}

// === Run 3: PROJECT_ASSIGNMENT ===

export async function runProjectAssignment(actorId: string): Promise<RunSummary> {
  const t0 = Date.now();
  await requirePrerequisite("PROJECT_ASSIGNMENT");
  await ensureNotFinalized("PROJECT_ASSIGNMENT");
  await clearDrafts("PROJECT_ASSIGNMENT");

  const config = await getConfig();
  const tempRunId = `temp-${Date.now()}`;

  const { autoFilledUserIds } = await persistAutoFill(
    "PROJECT_ASSIGNMENT",
    tempRunId,
    config
  );

  // Build project-assignment input. FCFS uses User.preferencesSubmittedAt;
  // null (auto-filled) goes LAST per SRS §7.5.
  const [podHeads, projects] = await Promise.all([
    db.podHeadProfile.findMany({
      select: {
        id: true,
        userId: true,
        user: { select: { preferencesSubmittedAt: true } },
        projectPicks: {
          orderBy: { rank: "asc" },
          select: { projectId: true }
        }
      }
    }),
    db.project.findMany({
      select: { id: true, capacity: true }
    })
  ]);

  const paInput: ProjectAssignmentInput = {
    podHeads: podHeads.map((p) => ({
      id: p.id,
      preferencesSubmittedAt: p.user.preferencesSubmittedAt
        ? p.user.preferencesSubmittedAt.toISOString()
        : null,
      projectPicks: p.projectPicks.map((pp) => pp.projectId)
    })),
    projects: projects.map((p) => ({
      id: p.id,
      capacity: p.capacity ?? config.defaultProjectCapacity
    })),
    projectsPerPodHead: config.projectsPerPodHead
  };

  const result = assignProjects(paInput);
  const durationMs = Date.now() - t0;

  // Persist draft. For project assignment, "placements" is a Pod-Head→
  // ordered-projects map, not a single matching pair. We stash it the
  // same way as HR placements so finalize can apply it.
  const run = await db.matchingRun.create({
    data: {
      type: "PROJECT_ASSIGNMENT",
      status: "COMPLETED",
      completedAt: new Date(),
      isFinalized: false,
      triggeredBy: actorId,
      autoFilledUsers: autoFilledUserIds,
      stats: {
        matchedCount: Object.keys(result.assignments).length,
        rosterSizes: result.loads,
        autoFilledCount: autoFilledUserIds.length,
        durationMs,
        assignments: result.assignments,
        dispositions: result.dispositions
      } satisfies Prisma.InputJsonValue
    }
  });

  return {
    runId: run.id,
    type: "PROJECT_ASSIGNMENT",
    isFinalized: false,
    stats: {
      matchedCount: Object.keys(result.assignments).length,
      rosterSizes: result.loads,
      autoFilledCount: autoFilledUserIds.length,
      durationMs
    }
  };
}

// === Helpers ===

interface DraftPayload {
  type: MatchType;
  actorId: string;
  autoFilledUserIds: string[];
  hrResult: { matched: Record<string, string | null>; rosters: Record<string, string[]>; stats: { totalProposals: number; rounds: number } };
  placements: Record<string, string | null>;
  rosters: Record<string, string[]>;
  durationMs: number;
}

async function persistDraft(payload: DraftPayload): Promise<RunSummary> {
  const rosterSizes: Record<string, number> = {};
  for (const [h, list] of Object.entries(payload.rosters)) {
    rosterSizes[h] = list.length;
  }
  const matchedCount = Object.values(payload.placements).filter(
    (v) => v !== null
  ).length;

  const run = await db.matchingRun.create({
    data: {
      type: payload.type,
      status: "COMPLETED",
      completedAt: new Date(),
      isFinalized: false,
      triggeredBy: payload.actorId,
      autoFilledUsers: payload.autoFilledUserIds,
      stats: {
        totalProposals: payload.hrResult.stats.totalProposals,
        rounds: payload.hrResult.stats.rounds,
        matchedCount,
        rosterSizes,
        autoFilledCount: payload.autoFilledUserIds.length,
        durationMs: payload.durationMs,
        placements: payload.placements,
        rosters: payload.rosters
      } satisfies Prisma.InputJsonValue
    }
  });

  return {
    runId: run.id,
    type: payload.type,
    isFinalized: false,
    stats: {
      totalProposals: payload.hrResult.stats.totalProposals,
      rounds: payload.hrResult.stats.rounds,
      matchedCount,
      rosterSizes,
      autoFilledCount: payload.autoFilledUserIds.length,
      durationMs: payload.durationMs
    }
  };
}

// === Finalize ===

export async function finalizeMatch(actorId: string, type: MatchType): Promise<void> {
  const draft = await db.matchingRun.findFirst({
    where: { type, isFinalized: false, status: "COMPLETED" },
    orderBy: { startedAt: "desc" }
  });
  if (!draft) {
    throw new Error(`No draft run to finalize for ${type}. Run a match first.`);
  }
  const stats = draft.stats as Record<string, unknown> | null;
  if (!stats) throw new Error("Draft has no stats payload.");

  if (type === "ORCH_PODHEAD") {
    const placements = (stats.placements ?? {}) as Record<string, string | null>;
    await db.$transaction(async (tx) => {
      // Apply each PodHead → Orch assignment
      for (const [podHeadId, orchId] of Object.entries(placements)) {
        if (orchId) {
          await tx.podHeadProfile.update({
            where: { id: podHeadId },
            data: { assignedOrchId: orchId }
          });
        }
      }
      await tx.matchingRun.update({
        where: { id: draft.id },
        data: { isFinalized: true, triggeredBy: actorId }
      });
    });
  } else if (type === "PODHEAD_AGENT") {
    const placements = (stats.placements ?? {}) as Record<string, string | null>;
    await db.$transaction(async (tx) => {
      for (const [agentId, podHeadId] of Object.entries(placements)) {
        if (podHeadId) {
          await tx.agentProfile.update({
            where: { id: agentId },
            data: { assignedPodHeadId: podHeadId }
          });
        }
      }
      await tx.matchingRun.update({
        where: { id: draft.id },
        data: { isFinalized: true, triggeredBy: actorId }
      });
    });
  } else {
    // PROJECT_ASSIGNMENT: the algorithm may assign a project NOT in the Pod
    // Head's original 2 picks (balance fallback per SRS §7.5). To honor
    // that, on finalize we wipe + replace the PodHeadProjectPick rows so
    // they reflect what was actually assigned. Original picks remain
    // captured in the immutable `MatchingRun.stats.assignments` /
    // `dispositions` payload — the transparency UI (Phase 8) joins both.
    const assignments = (stats.assignments ?? {}) as Record<string, string[]>;
    await db.$transaction(async (tx) => {
      for (const [podHeadId, projectIds] of Object.entries(assignments)) {
        await tx.podHeadProjectPick.deleteMany({ where: { podHeadId } });
        await tx.podHeadProjectPick.createMany({
          data: projectIds.map((projectId, idx) => ({
            podHeadId,
            projectId,
            rank: idx + 1,
            assigned: true,
            autoGenerated: false
          }))
        });
      }
      await tx.matchingRun.update({
        where: { id: draft.id },
        data: { isFinalized: true, triggeredBy: actorId }
      });
    });
  }
}

// === Rollback ===

export async function rollbackMatch(actorId: string, type: MatchType): Promise<void> {
  const finalized = await db.matchingRun.findFirst({
    where: { type, isFinalized: true, status: "COMPLETED" },
    orderBy: { startedAt: "desc" }
  });
  if (!finalized) {
    throw new Error(`No finalized run to roll back for ${type}.`);
  }

  if (type === "ORCH_PODHEAD") {
    await db.$transaction(async (tx) => {
      await tx.podHeadProfile.updateMany({ data: { assignedOrchId: null } });
      await tx.matchingRun.update({
        where: { id: finalized.id },
        data: { status: "ROLLED_BACK", triggeredBy: actorId }
      });
    });
  } else if (type === "PODHEAD_AGENT") {
    await db.$transaction(async (tx) => {
      await tx.agentProfile.updateMany({ data: { assignedPodHeadId: null } });
      await tx.matchingRun.update({
        where: { id: finalized.id },
        data: { status: "ROLLED_BACK", triggeredBy: actorId }
      });
    });
  } else {
    await db.$transaction(async (tx) => {
      await tx.podHeadProjectPick.updateMany({ data: { assigned: false } });
      await tx.matchingRun.update({
        where: { id: finalized.id },
        data: { status: "ROLLED_BACK", triggeredBy: actorId }
      });
    });
  }
}

// === Status ===

export async function getMatchingStatus(): Promise<MatchingStatus> {
  const types: MatchType[] = ["ORCH_PODHEAD", "PODHEAD_AGENT", "PROJECT_ASSIGNMENT"];
  const out: MatchingStatus = {
    ORCH_PODHEAD: { runId: null, isFinalized: false, stats: null },
    PODHEAD_AGENT: { runId: null, isFinalized: false, stats: null },
    PROJECT_ASSIGNMENT: { runId: null, isFinalized: false, stats: null }
  };
  for (const t of types) {
    const latest = await db.matchingRun.findFirst({
      where: { type: t, status: { not: "ROLLED_BACK" } },
      orderBy: { startedAt: "desc" }
    });
    if (latest) {
      const s = (latest.stats ?? {}) as Record<string, unknown>;
      out[t] = {
        runId: latest.id,
        isFinalized: latest.isFinalized,
        stats: {
          totalProposals: s.totalProposals as number | undefined,
          rounds: s.rounds as number | undefined,
          matchedCount: (s.matchedCount as number) ?? 0,
          rosterSizes: (s.rosterSizes as Record<string, number>) ?? {},
          autoFilledCount: (s.autoFilledCount as number) ?? 0,
          durationMs: (s.durationMs as number) ?? 0
        }
      };
    }
  }
  return out;
}
