"use server";

/**
 * Preference server actions (SRS §6.2–6.4, §12).
 *
 * Every action enforces:
 *   1. User is authenticated with the correct role.
 *   2. PREFERENCES phase is OPEN.
 *   3. User has completed their profile (profileCompletedAt is set).
 *   4. The submitted ids exist in the pool with the expected count.
 *
 * Saves are wipe-and-replace inside a transaction so the user's preferences
 * are always consistent on disk — never half-rank.
 *
 * `User.preferencesSubmittedAt` is set ONLY by `markPreferencesSubmitted`, not
 * by the per-task saves. This is used for FCFS in project assignment, so we
 * only stamp it once the user explicitly commits the whole bundle.
 */

import { z } from "zod";
import type { Prisma } from "@prisma/client";

import { db } from "@/lib/db";
import { getConfig } from "@/lib/config";
import {
  ForbiddenError,
  requireAuth,
  requireParticipant,
  requirePhase
} from "@/lib/permissions";

const idArray = z.array(z.string().min(1));

function requireDistinct(ids: string[]): string[] {
  const set = new Set(ids);
  if (set.size !== ids.length) {
    throw new Error("Duplicate selections are not allowed.");
  }
  return ids;
}

async function gate(role: "AGENT" | "POD_HEAD" | "ORCH") {
  await requirePhase("PREFERENCES", "OPEN");
  const user = await requireParticipant(role);
  if (!user.profileCompletedAt) {
    throw new ForbiddenError("Complete your profile first.");
  }
  return user;
}

// === Agent ranks Pod Heads ===

export async function saveAgentRankings(podHeadIds: string[]): Promise<void> {
  const user = await gate("AGENT");
  const config = await getConfig();
  const ids = requireDistinct(idArray.parse(podHeadIds));
  if (ids.length !== config.agentRanksTopNPodHeads) {
    throw new Error(
      `Rank exactly ${config.agentRanksTopNPodHeads} Pod Heads (got ${ids.length}).`
    );
  }

  // Pool validation: every id must be a real PodHeadProfile.
  const podHeads = await db.podHeadProfile.findMany({
    where: { id: { in: ids } },
    select: { id: true }
  });
  if (podHeads.length !== ids.length) {
    throw new Error("Some ranked Pod Heads no longer exist.");
  }

  const agent = await db.agentProfile.findUniqueOrThrow({
    where: { userId: user.id },
    select: { id: true }
  });

  await db.$transaction([
    db.agentPodHeadRanking.deleteMany({ where: { agentId: agent.id } }),
    db.agentPodHeadRanking.createMany({
      data: ids.map((podHeadId, i) => ({
        agentId: agent.id,
        podHeadId,
        rank: i + 1,
        autoGenerated: false
      }))
    })
  ]);
}

// === Pod Head: ranks Orchs ===

export async function savePodHeadOrchRankings(
  orchIds: string[]
): Promise<void> {
  const user = await gate("POD_HEAD");
  const config = await getConfig();
  const ids = requireDistinct(idArray.parse(orchIds));
  if (ids.length !== config.orchCount) {
    throw new Error(
      `Rank all ${config.orchCount} Orchs (got ${ids.length}).`
    );
  }

  const orchs = await db.orchProfile.findMany({
    where: { id: { in: ids } },
    select: { id: true }
  });
  if (orchs.length !== ids.length) {
    throw new Error("Some Orchs no longer exist.");
  }

  const podHead = await db.podHeadProfile.findUniqueOrThrow({
    where: { userId: user.id },
    select: { id: true }
  });

  await db.$transaction([
    db.podHeadOrchRanking.deleteMany({ where: { podHeadId: podHead.id } }),
    db.podHeadOrchRanking.createMany({
      data: ids.map((orchId, i) => ({
        podHeadId: podHead.id,
        orchId,
        rank: i + 1,
        autoGenerated: false
      }))
    })
  ]);
}

// === Pod Head: selects + ranks Agents ===

export async function savePodHeadAgentSelections(
  agentIds: string[]
): Promise<void> {
  const user = await gate("POD_HEAD");
  const config = await getConfig();
  const ids = requireDistinct(idArray.parse(agentIds));
  if (ids.length !== config.podHeadRanksTopNAgents) {
    throw new Error(
      `Select exactly ${config.podHeadRanksTopNAgents} Agents (got ${ids.length}).`
    );
  }

  const agents = await db.agentProfile.findMany({
    where: { id: { in: ids } },
    select: { id: true }
  });
  if (agents.length !== ids.length) {
    throw new Error("Some Agents no longer exist.");
  }

  const podHead = await db.podHeadProfile.findUniqueOrThrow({
    where: { userId: user.id },
    select: { id: true }
  });

  await db.$transaction([
    db.podHeadAgentSelection.deleteMany({ where: { podHeadId: podHead.id } }),
    db.podHeadAgentSelection.createMany({
      data: ids.map((agentId, i) => ({
        podHeadId: podHead.id,
        agentId,
        rank: i + 1,
        autoGenerated: false
      }))
    })
  ]);
}

// === Pod Head: picks 2 projects (primary + secondary) ===

export async function savePodHeadProjectPicks(
  projectIds: string[]
): Promise<void> {
  const user = await gate("POD_HEAD");
  const config = await getConfig();
  const ids = requireDistinct(idArray.parse(projectIds));
  if (ids.length !== config.projectsPerPodHead) {
    throw new Error(
      `Pick exactly ${config.projectsPerPodHead} projects (got ${ids.length}).`
    );
  }

  const projects = await db.project.findMany({
    where: { id: { in: ids } },
    select: { id: true }
  });
  if (projects.length !== ids.length) {
    throw new Error("Some projects no longer exist.");
  }

  const podHead = await db.podHeadProfile.findUniqueOrThrow({
    where: { userId: user.id },
    select: { id: true }
  });

  await db.$transaction([
    db.podHeadProjectPick.deleteMany({ where: { podHeadId: podHead.id } }),
    db.podHeadProjectPick.createMany({
      data: ids.map((projectId, i) => ({
        podHeadId: podHead.id,
        projectId,
        rank: i + 1,
        autoGenerated: false
      }))
    })
  ]);
}

// === Orch: selects + ranks Pod Heads ===

export async function saveOrchPodHeadSelections(
  podHeadIds: string[]
): Promise<void> {
  const user = await gate("ORCH");
  const config = await getConfig();
  const ids = requireDistinct(idArray.parse(podHeadIds));
  if (ids.length !== config.podHeadsPerOrch) {
    throw new Error(
      `Rank exactly ${config.podHeadsPerOrch} Pod Heads (got ${ids.length}).`
    );
  }

  const podHeads = await db.podHeadProfile.findMany({
    where: { id: { in: ids } },
    select: { id: true }
  });
  if (podHeads.length !== ids.length) {
    throw new Error("Some Pod Heads no longer exist.");
  }

  const orch = await db.orchProfile.findUniqueOrThrow({
    where: { userId: user.id },
    select: { id: true }
  });

  await db.$transaction([
    db.orchPodHeadSelection.deleteMany({ where: { orchId: orch.id } }),
    db.orchPodHeadSelection.createMany({
      data: ids.map((podHeadId, i) => ({
        orchId: orch.id,
        podHeadId,
        rank: i + 1,
        autoGenerated: false
      }))
    })
  ]);
}

// === Final submit: stamps preferencesSubmittedAt (used for FCFS) ===

interface SubmitStatus {
  ok: boolean;
  missing: string[]; // task names the user hasn't finished
}

export async function markPreferencesSubmitted(): Promise<SubmitStatus> {
  await requirePhase("PREFERENCES", "OPEN");
  const user = await requireAuth();
  if (!user.profileCompletedAt) {
    throw new ForbiddenError("Complete your profile first.");
  }
  const missing = await collectMissingTasks({ id: user.id, role: user.role });
  if (missing.length > 0) {
    return { ok: false, missing };
  }
  // Idempotent: only stamp the first time (FCFS uses this timestamp).
  await db.user.update({
    where: { id: user.id, preferencesSubmittedAt: null },
    data: { preferencesSubmittedAt: new Date() }
  }).catch(() => {
    // already submitted — fine
  });
  return { ok: true, missing: [] };
}

// Helper: which tasks does this user still owe?
async function collectMissingTasks(user: {
  id: string;
  role: "AGENT" | "POD_HEAD" | "ORCH";
}): Promise<string[]> {
  const config = await getConfig();
  const missing: string[] = [];

  if (user.role === "AGENT") {
    const agent = await db.agentProfile.findUnique({
      where: { userId: user.id },
      select: { id: true }
    });
    if (!agent) return ["agent profile"];
    const count = await db.agentPodHeadRanking.count({
      where: { agentId: agent.id }
    });
    if (count !== config.agentRanksTopNPodHeads) missing.push("rank Pod Heads");
  } else if (user.role === "POD_HEAD") {
    const ph = await db.podHeadProfile.findUnique({
      where: { userId: user.id },
      select: { id: true }
    });
    if (!ph) return ["pod head profile"];
    const [orchs, agents, projects] = await Promise.all([
      db.podHeadOrchRanking.count({ where: { podHeadId: ph.id } }),
      db.podHeadAgentSelection.count({ where: { podHeadId: ph.id } }),
      db.podHeadProjectPick.count({ where: { podHeadId: ph.id } })
    ]);
    if (orchs !== config.orchCount) missing.push("rank Orchs");
    if (agents !== config.podHeadRanksTopNAgents) missing.push("rank Agents");
    if (projects !== config.projectsPerPodHead) missing.push("pick Projects");
  } else if (user.role === "ORCH") {
    const orch = await db.orchProfile.findUnique({
      where: { userId: user.id },
      select: { id: true }
    });
    if (!orch) return ["orch profile"];
    const count = await db.orchPodHeadSelection.count({
      where: { orchId: orch.id }
    });
    if (count !== config.podHeadsPerOrch) missing.push("rank Pod Heads");
  }

  return missing;
}

// Make Prisma's JSON type available to callers if needed.
export type AuditDetailsValue = Prisma.InputJsonValue;
