/**
 * Shared types for the matching engine.
 *
 * IMPORTANT (per SRS §3.3, §7): this module is framework-agnostic and pure TS.
 * It MUST NOT import from @prisma/client or any database/I/O. All inputs are
 * plain values; all outputs are plain values. This is what makes the engine
 * unit-testable in isolation against the §14.2 test cases.
 */

// === Generic Hospital-Residents (Gale-Shapley many-to-one) ===

/** A resident (the proposing side). Preferences are ordered, rank 1 first. */
export interface Resident<TId extends string = string> {
  id: TId;
  /** Ordered hospital ids, position 0 = top pick. */
  preferences: TId[];
}

/** A hospital (the receiving side). Capacity bounds the roster. */
export interface Hospital<TId extends string = string> {
  id: TId;
  capacity: number;
  /** Ordered resident ids, position 0 = top pick. */
  preferences: TId[];
}

export interface HRInput<TId extends string = string> {
  residents: Resident<TId>[];
  hospitals: Hospital<TId>[];
}

export interface HRResult<TId extends string = string> {
  /** residentId → hospitalId (null if straggler). */
  matched: Record<TId, TId | null>;
  /** hospitalId → ordered list of residentIds (sorted by hospital's preference). */
  rosters: Record<TId, TId[]>;
  /** residentIds whose preferences were exhausted without a match. */
  stragglers: TId[];
  /** Stats reported per SRS §7.7. */
  stats: {
    totalProposals: number;
    rounds: number;
  };
}

// === Completion pass ===

/** Same shape as HRResult after stragglers have been placed. */
export type CompletedHRResult<TId extends string = string> = Omit<
  HRResult<TId>,
  "stragglers"
> & {
  /** residentIds placed by completion pass (subset of original stragglers). */
  completedPlacements: TId[];
};

// === Project assignment ===

export interface PodHeadForProjects<TId extends string = string> {
  id: TId;
  /** ISO timestamp string, or null if auto-filled (treated as "last"). */
  preferencesSubmittedAt: string | null;
  /** Length === EventConfig.projectsPerPodHead. Index 0 = primary, 1 = secondary. */
  projectPicks: TId[];
}

export interface ProjectInput<TId extends string = string> {
  id: TId;
  capacity: number;
}

export interface ProjectAssignmentInput<TId extends string = string> {
  podHeads: PodHeadForProjects<TId>[];
  projects: ProjectInput<TId>[];
  /** EventConfig.projectsPerPodHead (default 2). */
  projectsPerPodHead: number;
}

export interface ProjectAssignmentResult<TId extends string = string> {
  /** podHeadId → ordered project ids (length === projectsPerPodHead). */
  assignments: Record<TId, TId[]>;
  /** projectId → final headcount. */
  loads: Record<TId, number>;
  /** Per-PodHead per-rank disposition for the transparency UI. */
  dispositions: Array<{
    podHeadId: TId;
    rank: number; // 1 = primary slot, 2 = secondary slot, …
    projectId: TId;
    /** What happened for this slot. */
    outcome: "PRIMARY_HONORED" | "SECONDARY_HONORED" | "FELL_BACK_TO_BALANCE";
  }>;
}

// === Auto-fill ===

export type MatchType = "ORCH_PODHEAD" | "PODHEAD_AGENT" | "PROJECT_ASSIGNMENT";

/** Deterministic seeded RNG factory. */
export type Rng = () => number;

/**
 * A single auto-generated preference row to be persisted. The matching engine
 * is pure, so callers (e.g. Phase 7's API route) translate these into Prisma
 * inserts. `autoGenerated = true` is implied.
 */
export interface AutoFillRow<TId extends string = string> {
  fromId: TId;
  toId: TId;
  rank: number;
}

export interface AutoFillInput<TId extends string = string> {
  matchType: MatchType;
  runId: string;
  /** All Pod Heads in the system (id only). */
  podHeads: TId[];
  /** All Orchs in the system (id only). */
  orchs: TId[];
  /** All Agents in the system (id only). */
  agents: TId[];
  /** All Projects (id only). */
  projects: TId[];
  /** Pod Head ids that submitted ranks of Orchs. */
  podHeadsWhoRankedOrchs: Set<TId>;
  /** Orch ids that submitted selections of Pod Heads. */
  orchsWhoSelectedPodHeads: Set<TId>;
  /** Pod Head ids that submitted selections of Agents. */
  podHeadsWhoSelectedAgents: Set<TId>;
  /** Agent ids that submitted ranks of Pod Heads. */
  agentsWhoRankedPodHeads: Set<TId>;
  /** Pod Head ids that submitted project picks. */
  podHeadsWhoPickedProjects: Set<TId>;
  /** Sizes from EventConfig. */
  config: {
    podHeadsPerOrch: number;
    agentsPerPodHead: number;
    agentRanksTopNPodHeads: number;
    podHeadRanksTopNAgents: number;
    projectsPerPodHead: number;
  };
}

export interface AutoFillResult<TId extends string = string> {
  /** Where to write each set of rows. */
  podHeadOrchRankings: AutoFillRow<TId>[];
  orchPodHeadSelections: AutoFillRow<TId>[];
  podHeadAgentSelections: AutoFillRow<TId>[];
  agentPodHeadRankings: AutoFillRow<TId>[];
  podHeadProjectPicks: AutoFillRow<TId>[];
  /** Distinct user ids whose preferences were generated (for MatchingRun.autoFilledUsers). */
  autoFilledUserIds: TId[];
}
