/**
 * Orch dashboard (SRS §6.2).
 *
 * Server component. Loads the EventConfig, current PREFERENCES phase status,
 * the full Pod Head pool, and any existing selection rows for this Orch. The
 * interactive picker is the only `'use client'` boundary on this route.
 */

import { requireParticipant } from "@/lib/permissions";
import { signOut } from "@/auth";
import { db } from "@/lib/db";
import { getConfig } from "@/lib/config";
import { getOrchResults, type OrchPodHeadEntry } from "@/lib/results";
import { PitchCard } from "@/components/PitchCard";
import { TransparencyBadge } from "@/components/TransparencyBadge";

import { OrchRankPicker, type PodHeadOption } from "./OrchRankPicker";

export const dynamic = "force-dynamic";

export default async function OrchPage() {
  const user = await requireParticipant("ORCH");

  const [config, preferencesPhase, resultsPhase] = await Promise.all([
    getConfig(),
    db.eventPhase.findUnique({ where: { name: "PREFERENCES" } }),
    db.eventPhase.findUnique({ where: { name: "RESULTS_PUBLISHED" } })
  ]);

  const resultsOpen = resultsPhase?.status === "OPEN";
  const isOpen = preferencesPhase?.status === "OPEN";

  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <header className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">
            Orch Dashboard
          </h1>
          <p className="mt-1 text-sm text-zinc-500">
            Welcome, {user.name} ({user.email})
          </p>
        </div>
        <form
          action={async () => {
            "use server";
            await signOut({ redirectTo: "/signin" });
          }}
        >
          <button
            type="submit"
            className="rounded-md border border-zinc-300 px-3 py-1.5 text-sm hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-900"
          >
            Sign out
          </button>
        </form>
      </header>

      {resultsOpen ? (
        <OrchResultsView
          orchUserId={user.id}
          podHeadsPerOrch={config.podHeadsPerOrch}
          orchCount={config.orchCount}
        />
      ) : isOpen ? (
        <OrchPreferences orchUserId={user.id} targetCount={config.podHeadsPerOrch} />
      ) : (
        <section className="mt-10 rounded-md border border-zinc-200 bg-zinc-50 px-4 py-6 text-sm text-zinc-600 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
          Preferences are not open right now. Check back when the admin opens
          the preference window.
        </section>
      )}
    </main>
  );
}

async function OrchResultsView({
  orchUserId,
  podHeadsPerOrch,
  orchCount
}: {
  orchUserId: string;
  podHeadsPerOrch: number;
  orchCount: number;
}) {
  const results = await getOrchResults(orchUserId);

  if (results.assignedPodHeads.length === 0) {
    return (
      <section className="mt-10 rounded-md border border-zinc-200 bg-zinc-50 px-4 py-6 text-sm text-zinc-600 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
        Results haven&rsquo;t been finalized yet. Check back once the admin
        publishes the final assignments.
      </section>
    );
  }

  return (
    <section className="mt-10">
      <div className="mb-6">
        <h2 className="text-xl font-semibold tracking-tight">Your Pod Heads</h2>
        <p className="mt-1 text-sm text-zinc-500">
          {results.assignedPodHeads.length} Pod Head
          {results.assignedPodHeads.length === 1 ? "" : "s"} assigned. Expand
          each one to see their pod of agents and projects.
        </p>
      </div>

      <ul className="grid gap-4">
        {results.assignedPodHeads.map((ph) => (
          <li key={ph.id}>
            <OrchPodHeadCard
              podHead={ph}
              podHeadsPerOrch={podHeadsPerOrch}
              orchCount={orchCount}
            />
          </li>
        ))}
      </ul>
    </section>
  );
}

function OrchPodHeadCard({
  podHead,
  podHeadsPerOrch,
  orchCount
}: {
  podHead: OrchPodHeadEntry;
  podHeadsPerOrch: number;
  orchCount: number;
}) {
  return (
    <div className="rounded-md border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950">
      <div className="mb-3 flex flex-wrap items-center gap-2">
        {podHead.autoGenerated ? (
          <TransparencyBadge variant="auto-assigned" />
        ) : (
          <>
            {podHead.rankAchieved !== null ? (
              <TransparencyBadge
                variant="rank-achieved"
                rank={podHead.rankAchieved}
                outOf={podHeadsPerOrch}
              />
            ) : null}
            {podHead.theirRankOfYou !== null ? (
              <TransparencyBadge
                variant="their-rank"
                rank={podHead.theirRankOfYou}
                outOf={orchCount}
              />
            ) : null}
          </>
        )}
      </div>

      <PitchCard
        name={podHead.name}
        role="POD_HEAD"
        email={podHead.email}
        bio={podHead.bio}
        skills={podHead.skills}
        pitch={podHead.pitch}
      />

      <details className="mt-3 group">
        <summary className="cursor-pointer text-xs font-medium text-zinc-700 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100">
          View pod ({podHead.agents.length} agent
          {podHead.agents.length === 1 ? "" : "s"}, {podHead.projects.length}{" "}
          project{podHead.projects.length === 1 ? "" : "s"})
        </summary>

        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div>
            <h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              Agents
            </h4>
            {podHead.agents.length === 0 ? (
              <p className="text-xs text-zinc-500">No agents assigned.</p>
            ) : (
              <ul className="list-disc space-y-1 pl-5 text-sm text-zinc-800 dark:text-zinc-200">
                {podHead.agents.map((a) => (
                  <li key={a.id}>
                    <span className="font-medium">{a.name}</span>
                    {a.skills.length > 0 ? (
                      <span className="text-zinc-500"> &mdash; {a.skills.join(", ")}</span>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div>
            <h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              Projects
            </h4>
            {podHead.projects.length === 0 ? (
              <p className="text-xs text-zinc-500">No projects assigned.</p>
            ) : (
              <ul className="list-disc space-y-1 pl-5 text-sm text-zinc-800 dark:text-zinc-200">
                {podHead.projects.map((p) => (
                  <li key={p.id}>
                    <span className="font-medium">{p.title}</span>
                    {p.tags.length > 0 ? (
                      <span className="text-zinc-500"> &mdash; {p.tags.join(", ")}</span>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </details>
    </div>
  );
}

async function OrchPreferences({
  orchUserId,
  targetCount
}: {
  orchUserId: string;
  targetCount: number;
}) {
  // The Orch's own profile row — needed to read existing selections.
  const orch = await db.orchProfile.findUnique({
    where: { userId: orchUserId },
    select: {
      podHeadSelections: {
        orderBy: { rank: "asc" },
        select: { podHeadId: true }
      }
    }
  });

  const podHeadRows = await db.podHeadProfile.findMany({
    select: {
      id: true,
      bio: true,
      skills: true,
      pitch: true,
      user: { select: { name: true, email: true } }
    },
    orderBy: { user: { name: "asc" } }
  });

  const podHeads: PodHeadOption[] = podHeadRows.map((ph) => ({
    id: ph.id,
    name: ph.user.name,
    email: ph.user.email,
    bio: ph.bio,
    skills: ph.skills,
    pitch: ph.pitch
  }));

  const initialSelectedIds = orch?.podHeadSelections.map((s) => s.podHeadId) ?? [];

  // The User.preferencesSubmittedAt timestamp drives the "Submitted on…" copy.
  const userRecord = await db.user.findUnique({
    where: { id: orchUserId },
    select: { preferencesSubmittedAt: true }
  });

  return (
    <OrchRankPicker
      podHeads={podHeads}
      initialSelectedIds={initialSelectedIds}
      targetCount={targetCount}
      initialSubmittedAt={
        userRecord?.preferencesSubmittedAt
          ? userRecord.preferencesSubmittedAt.toISOString()
          : null
      }
    />
  );
}
