/**
 * Orch dashboard (SRS §6.2).
 *
 * Server component. Loads the EventConfig, current PREFERENCES phase status,
 * the full Pod Head pool, and any existing selection rows for this Orch. The
 * interactive picker is the only `'use client'` boundary on this route.
 */

import { AppFooter } from "@/components/chrome/AppFooter";
import { AppHeader } from "@/components/chrome/AppHeader";
import { PageHeader } from "@/components/chrome/PageHeader";
import { SectionBanner } from "@/components/chrome/SectionBanner";
import { PitchCard } from "@/components/PitchCard";
import { TransparencyBadge } from "@/components/TransparencyBadge";
import { Alert } from "@/components/ui/alert";
import { Card } from "@/components/ui/card";
import { getConfig } from "@/lib/config";
import { db } from "@/lib/db";
import { requireParticipant } from "@/lib/permissions";
import { getOrchResults, type OrchPodHeadEntry } from "@/lib/results";

import { OrchRankPicker, type PodHeadOption } from "./OrchRankPicker";

export const dynamic = "force-dynamic";

export default async function OrchPage() {
  const user = await requireParticipant("ORCH");

  const [config, preferencesPhase, resultsPhase] = await Promise.all([
    getConfig(),
    db.eventPhase.findUnique({ where: { name: "PREFERENCES" } }),
    db.eventPhase.findUnique({ where: { name: "RESULTS_PUBLISHED" } })
  ]);

  const resultsOpen = resultsPhase?.status === "OPEN";
  const isOpen = preferencesPhase?.status === "OPEN";

  return (
    <div className="min-h-screen bg-surface">
      <AppHeader user={{ email: user.email }} />
      <PageHeader
        eyebrow="Orch"
        title={resultsOpen ? "Your Pod Heads" : "Orch dashboard"}
        subtitle={`Welcome, ${user.name} — ${user.email}`}
      />
      <main className="mx-auto max-w-6xl px-6 py-10">
        {resultsOpen ? (
          <OrchResultsView
            orchUserId={user.id}
            podHeadsPerOrch={config.podHeadsPerOrch}
            orchCount={config.orchCount}
          />
        ) : isOpen ? (
          <OrchPreferences
            orchUserId={user.id}
            targetCount={config.podHeadsPerOrch}
          />
        ) : (
          <Alert variant="warning" title="Preferences are not open right now">
            Check back when the admin opens the preference window.
          </Alert>
        )}
      </main>
      <AppFooter />
    </div>
  );
}

async function OrchResultsView({
  orchUserId,
  podHeadsPerOrch,
  orchCount
}: {
  orchUserId: string;
  podHeadsPerOrch: number;
  orchCount: number;
}) {
  const results = await getOrchResults(orchUserId);

  if (results.assignedPodHeads.length === 0) {
    return (
      <Alert variant="neutral" title="Results haven't been finalized yet">
        Check back once the admin publishes the final assignments.
      </Alert>
    );
  }

  return (
    <section>
      <SectionBanner
        title="Your Pod Heads"
        subtitle={`${results.assignedPodHeads.length} Pod Head${
          results.assignedPodHeads.length === 1 ? "" : "s"
        } assigned. Expand each one to see their pod of agents and projects.`}
      />

      <ul className="mt-8 grid gap-4">
        {results.assignedPodHeads.map((ph) => (
          <li key={ph.id}>
            <OrchPodHeadCard
              podHead={ph}
              podHeadsPerOrch={podHeadsPerOrch}
              orchCount={orchCount}
            />
          </li>
        ))}
      </ul>
    </section>
  );
}

function OrchPodHeadCard({
  podHead,
  podHeadsPerOrch,
  orchCount
}: {
  podHead: OrchPodHeadEntry;
  podHeadsPerOrch: number;
  orchCount: number;
}) {
  return (
    <Card>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        {podHead.autoGenerated ? (
          <TransparencyBadge variant="auto-assigned" />
        ) : (
          <>
            {podHead.rankAchieved !== null ? (
              <TransparencyBadge
                variant="rank-achieved"
                rank={podHead.rankAchieved}
                outOf={podHeadsPerOrch}
              />
            ) : null}
            {podHead.theirRankOfYou !== null ? (
              <TransparencyBadge
                variant="their-rank"
                rank={podHead.theirRankOfYou}
                outOf={orchCount}
              />
            ) : null}
          </>
        )}
      </div>

      <PitchCard
        name={podHead.name}
        role="POD_HEAD"
        email={podHead.email}
        bio={podHead.bio}
        skills={podHead.skills}
        pitch={podHead.pitch}
      />

      <details className="mt-3 group">
        <summary className="cursor-pointer text-xs font-medium text-brand-accent hover:underline">
          View pod ({podHead.agents.length} agent
          {podHead.agents.length === 1 ? "" : "s"}, {podHead.projects.length}{" "}
          project{podHead.projects.length === 1 ? "" : "s"})
        </summary>

        <div className="mt-3 grid gap-4 md:grid-cols-2">
          <div>
            <h4 className="mb-2 font-display text-xs font-semibold uppercase tracking-wide text-fg-muted">
              Agents
            </h4>
            {podHead.agents.length === 0 ? (
              <p className="text-xs text-fg-muted">No agents assigned.</p>
            ) : (
              <ul className="list-disc space-y-1 pl-5 text-sm text-fg">
                {podHead.agents.map((a) => (
                  <li key={a.id}>
                    <span className="font-medium">{a.name}</span>
                    {a.skills.length > 0 ? (
                      <span className="text-fg-muted">
                        {" "}
                        &mdash; {a.skills.join(", ")}
                      </span>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div>
            <h4 className="mb-2 font-display text-xs font-semibold uppercase tracking-wide text-fg-muted">
              Projects
            </h4>
            {podHead.projects.length === 0 ? (
              <p className="text-xs text-fg-muted">No projects assigned.</p>
            ) : (
              <ul className="list-disc space-y-1 pl-5 text-sm text-fg">
                {podHead.projects.map((p) => (
                  <li key={p.id}>
                    <span className="font-medium">{p.title}</span>
                    {p.tags.length > 0 ? (
                      <span className="text-fg-muted">
                        {" "}
                        &mdash; {p.tags.join(", ")}
                      </span>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </details>
    </Card>
  );
}

async function OrchPreferences({
  orchUserId,
  targetCount
}: {
  orchUserId: string;
  targetCount: number;
}) {
  const orch = await db.orchProfile.findUnique({
    where: { userId: orchUserId },
    select: {
      podHeadSelections: {
        orderBy: { rank: "asc" },
        select: { podHeadId: true }
      }
    }
  });

  const podHeadRows = await db.podHeadProfile.findMany({
    select: {
      id: true,
      bio: true,
      skills: true,
      pitch: true,
      user: { select: { name: true, email: true } }
    },
    orderBy: { user: { name: "asc" } }
  });

  const podHeads: PodHeadOption[] = podHeadRows.map((ph) => ({
    id: ph.id,
    name: ph.user.name,
    email: ph.user.email,
    bio: ph.bio,
    skills: ph.skills,
    pitch: ph.pitch
  }));

  const initialSelectedIds =
    orch?.podHeadSelections.map((s) => s.podHeadId) ?? [];

  const userRecord = await db.user.findUnique({
    where: { id: orchUserId },
    select: { preferencesSubmittedAt: true }
  });

  return (
    <OrchRankPicker
      podHeads={podHeads}
      initialSelectedIds={initialSelectedIds}
      targetCount={targetCount}
      initialSubmittedAt={
        userRecord?.preferencesSubmittedAt
          ? userRecord.preferencesSubmittedAt.toISOString()
          : null
      }
    />
  );
}
