-- CreateEnum
CREATE TYPE "Role" AS ENUM ('AGENT', 'POD_HEAD', 'ORCH');

-- CreateEnum
CREATE TYPE "PhaseName" AS ENUM ('REGISTRATION', 'PREFERENCES', 'MATCHING', 'RESULTS_PUBLISHED');

-- CreateEnum
CREATE TYPE "PhaseStatus" AS ENUM ('LOCKED', 'OPEN', 'CLOSED');

-- CreateEnum
CREATE TYPE "MatchType" AS ENUM ('ORCH_PODHEAD', 'PODHEAD_AGENT', 'PROJECT_ASSIGNMENT');

-- CreateEnum
CREATE TYPE "RunStatus" AS ENUM ('RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK');

-- CreateTable
CREATE TABLE "EventConfig" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "orchCount" INTEGER NOT NULL DEFAULT 5,
    "podHeadCount" INTEGER NOT NULL DEFAULT 60,
    "projectCount" INTEGER NOT NULL DEFAULT 12,
    "podHeadsPerOrch" INTEGER NOT NULL DEFAULT 12,
    "agentsPerPodHead" INTEGER NOT NULL DEFAULT 10,
    "projectsPerPodHead" INTEGER NOT NULL DEFAULT 2,
    "defaultProjectCapacity" INTEGER NOT NULL DEFAULT 10,
    "agentRanksTopNPodHeads" INTEGER NOT NULL DEFAULT 10,
    "podHeadRanksTopNAgents" INTEGER NOT NULL DEFAULT 10,
    "pitchMinChars" INTEGER NOT NULL DEFAULT 50,
    "pitchMaxChars" INTEGER NOT NULL DEFAULT 500,
    "allowedEmailDomains" TEXT[] DEFAULT ARRAY['tkxel.com']::TEXT[],
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventConfig_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "image" TEXT,
    "role" "Role" NOT NULL DEFAULT 'AGENT',
    "isAdmin" BOOLEAN NOT NULL DEFAULT false,
    "profileCompletedAt" TIMESTAMP(3),
    "preferencesSubmittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OrchProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "bio" TEXT,
    "pitch" TEXT NOT NULL,

    CONSTRAINT "OrchProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PodHeadProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "bio" TEXT,
    "skills" TEXT[],
    "pitch" TEXT NOT NULL,
    "assignedOrchId" TEXT,

    CONSTRAINT "PodHeadProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgentProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "bio" TEXT,
    "skills" TEXT[],
    "pitch" TEXT NOT NULL,
    "assignedPodHeadId" TEXT,

    CONSTRAINT "AgentProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "tags" TEXT[],
    "capacity" INTEGER,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgentPodHeadRanking" (
    "id" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "podHeadId" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AgentPodHeadRanking_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PodHeadAgentSelection" (
    "id" TEXT NOT NULL,
    "podHeadId" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PodHeadAgentSelection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PodHeadOrchRanking" (
    "id" TEXT NOT NULL,
    "podHeadId" TEXT NOT NULL,
    "orchId" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "PodHeadOrchRanking_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OrchPodHeadSelection" (
    "id" TEXT NOT NULL,
    "orchId" TEXT NOT NULL,
    "podHeadId" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "OrchPodHeadSelection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PodHeadProjectPick" (
    "id" TEXT NOT NULL,
    "podHeadId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "assigned" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "PodHeadProjectPick_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EventPhase" (
    "name" "PhaseName" NOT NULL,
    "status" "PhaseStatus" NOT NULL,
    "openedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "notes" TEXT,

    CONSTRAINT "EventPhase_pkey" PRIMARY KEY ("name")
);

-- CreateTable
CREATE TABLE "MatchingRun" (
    "id" TEXT NOT NULL,
    "type" "MatchType" NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "status" "RunStatus" NOT NULL,
    "stats" JSONB,
    "isFinalized" BOOLEAN NOT NULL DEFAULT false,
    "triggeredBy" TEXT NOT NULL,
    "inputSnapshot" JSONB,
    "autoFilledUsers" TEXT[],

    CONSTRAINT "MatchingRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "target" TEXT,
    "details" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "User_role_idx" ON "User"("role");

-- CreateIndex
CREATE INDEX "User_preferencesSubmittedAt_idx" ON "User"("preferencesSubmittedAt");

-- CreateIndex
CREATE UNIQUE INDEX "OrchProfile_userId_key" ON "OrchProfile"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadProfile_userId_key" ON "PodHeadProfile"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "AgentProfile_userId_key" ON "AgentProfile"("userId");

-- CreateIndex
CREATE INDEX "AgentPodHeadRanking_podHeadId_idx" ON "AgentPodHeadRanking"("podHeadId");

-- CreateIndex
CREATE UNIQUE INDEX "AgentPodHeadRanking_agentId_podHeadId_key" ON "AgentPodHeadRanking"("agentId", "podHeadId");

-- CreateIndex
CREATE UNIQUE INDEX "AgentPodHeadRanking_agentId_rank_key" ON "AgentPodHeadRanking"("agentId", "rank");

-- CreateIndex
CREATE INDEX "PodHeadAgentSelection_agentId_idx" ON "PodHeadAgentSelection"("agentId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadAgentSelection_podHeadId_agentId_key" ON "PodHeadAgentSelection"("podHeadId", "agentId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadAgentSelection_podHeadId_rank_key" ON "PodHeadAgentSelection"("podHeadId", "rank");

-- CreateIndex
CREATE INDEX "PodHeadOrchRanking_orchId_idx" ON "PodHeadOrchRanking"("orchId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadOrchRanking_podHeadId_orchId_key" ON "PodHeadOrchRanking"("podHeadId", "orchId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadOrchRanking_podHeadId_rank_key" ON "PodHeadOrchRanking"("podHeadId", "rank");

-- CreateIndex
CREATE INDEX "OrchPodHeadSelection_podHeadId_idx" ON "OrchPodHeadSelection"("podHeadId");

-- CreateIndex
CREATE UNIQUE INDEX "OrchPodHeadSelection_orchId_podHeadId_key" ON "OrchPodHeadSelection"("orchId", "podHeadId");

-- CreateIndex
CREATE UNIQUE INDEX "OrchPodHeadSelection_orchId_rank_key" ON "OrchPodHeadSelection"("orchId", "rank");

-- CreateIndex
CREATE INDEX "PodHeadProjectPick_projectId_idx" ON "PodHeadProjectPick"("projectId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadProjectPick_podHeadId_projectId_key" ON "PodHeadProjectPick"("podHeadId", "projectId");

-- CreateIndex
CREATE UNIQUE INDEX "PodHeadProjectPick_podHeadId_rank_key" ON "PodHeadProjectPick"("podHeadId", "rank");

-- CreateIndex
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- AddForeignKey
ALTER TABLE "OrchProfile" ADD CONSTRAINT "OrchProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadProfile" ADD CONSTRAINT "PodHeadProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadProfile" ADD CONSTRAINT "PodHeadProfile_assignedOrchId_fkey" FOREIGN KEY ("assignedOrchId") REFERENCES "OrchProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentProfile" ADD CONSTRAINT "AgentProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentProfile" ADD CONSTRAINT "AgentProfile_assignedPodHeadId_fkey" FOREIGN KEY ("assignedPodHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentPodHeadRanking" ADD CONSTRAINT "AgentPodHeadRanking_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "AgentProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgentPodHeadRanking" ADD CONSTRAINT "AgentPodHeadRanking_podHeadId_fkey" FOREIGN KEY ("podHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadAgentSelection" ADD CONSTRAINT "PodHeadAgentSelection_podHeadId_fkey" FOREIGN KEY ("podHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadAgentSelection" ADD CONSTRAINT "PodHeadAgentSelection_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "AgentProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadOrchRanking" ADD CONSTRAINT "PodHeadOrchRanking_podHeadId_fkey" FOREIGN KEY ("podHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadOrchRanking" ADD CONSTRAINT "PodHeadOrchRanking_orchId_fkey" FOREIGN KEY ("orchId") REFERENCES "OrchProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrchPodHeadSelection" ADD CONSTRAINT "OrchPodHeadSelection_orchId_fkey" FOREIGN KEY ("orchId") REFERENCES "OrchProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrchPodHeadSelection" ADD CONSTRAINT "OrchPodHeadSelection_podHeadId_fkey" FOREIGN KEY ("podHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadProjectPick" ADD CONSTRAINT "PodHeadProjectPick_podHeadId_fkey" FOREIGN KEY ("podHeadId") REFERENCES "PodHeadProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PodHeadProjectPick" ADD CONSTRAINT "PodHeadProjectPick_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
