/**
 * Visual ranked-preference tree.
 *
 * Renders a root card at the top and one or more "branches" beneath it.
 * Each branch has a labeled title pill and a vertical list of ranked nodes
 * connected with L-shaped ASCII-style connectors (├─ for middle rows, └─
 * for the last row). Pure presentational. Server-renderable.
 */

import type { Role } from "@prisma/client";
import type { ReactNode } from "react";

export interface PreferenceTreeNode {
  /** Visible rank number shown in the circle badge. */
  rank: number;
  /** Primary label, usually the person/project name. */
  name: string;
  /** Optional role chip (AGENT / POD_HEAD / ORCH). */
  role?: Role;
  /** Optional sub-line (department, project tag, etc.). */
  subtitle?: string;
  /** Optional badges row — typically one or more <TransparencyBadge /> instances. */
  badges?: ReactNode;
  /** Dim the row + show an amber border accent. */
  autoGenerated?: boolean;
  /** Highlight as the user's finalized assignment. */
  matched?: boolean;
}

export interface PreferenceBranchData {
  /** Title shown in the pill (e.g. "Pod Head Priorities"). */
  title: string;
  /** Optional one-line hint shown below the title pill. */
  caption?: string;
  /** Message rendered when items is empty. */
  emptyMessage: string;
  items: PreferenceTreeNode[];
}

interface PreferenceTreeProps {
  /** Header card content rendered at the root of the tree. */
  root: ReactNode;
  branches: PreferenceBranchData[];
}

const ROLE_BADGE: Record<Role, string> = {
  ORCH: "bg-violet-100 text-violet-900 dark:bg-violet-900 dark:text-violet-100",
  POD_HEAD: "bg-sky-100 text-sky-900 dark:bg-sky-900 dark:text-sky-100",
  AGENT: "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300"
};

export function PreferenceTree({ root, branches }: PreferenceTreeProps) {
  return (
    <div>
      <div className="rounded-md border border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-950">
        {root}
      </div>
      {branches.length > 0 && (
        <div
          aria-hidden
          className="ml-4 h-6 -translate-x-px border-l-2 border-zinc-200 dark:border-zinc-800"
        />
      )}
      <div className="space-y-6">
        {branches.map((branch, i) => (
          <PreferenceBranch
            key={`${branch.title}-${i}`}
            {...branch}
            isLast={i === branches.length - 1}
          />
        ))}
      </div>
    </div>
  );
}

function PreferenceBranch({
  title,
  caption,
  emptyMessage,
  items,
  isLast
}: PreferenceBranchData & { isLast: boolean }) {
  return (
    <section className="relative">
      {/* Title pill anchored on the vertical line */}
      <div className="relative pl-8">
        <span
          aria-hidden
          className="absolute left-4 top-0 bottom-0 -translate-x-px border-l-2 border-zinc-200 dark:border-zinc-800"
        />
        <span className="inline-flex items-center rounded-full bg-zinc-100 px-3 py-1 text-xs font-medium uppercase tracking-wider text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300">
          {title}
        </span>
        {caption ? (
          <p className="mt-1 text-xs text-zinc-500">{caption}</p>
        ) : null}
      </div>

      {/* Vertical spacer linking title to first child */}
      <div
        aria-hidden
        className="ml-4 h-4 -translate-x-px border-l-2 border-zinc-200 dark:border-zinc-800"
      />

      {items.length === 0 ? (
        <div className="ml-8 rounded-md border border-dashed border-zinc-300 px-4 py-6 text-center text-sm text-zinc-500 dark:border-zinc-700">
          {emptyMessage}
        </div>
      ) : (
        <ol className="space-y-2">
          {items.map((item, idx) => (
            <PreferenceNode
              key={`${item.rank}-${item.name}`}
              item={item}
              isLast={idx === items.length - 1}
            />
          ))}
        </ol>
      )}

      {/* Continuation line under the branch (so stacked branches stay visually
          connected). Suppressed on the final branch. */}
      {!isLast && (
        <div
          aria-hidden
          className="ml-4 mt-2 h-6 -translate-x-px border-l-2 border-zinc-200 dark:border-zinc-800"
        />
      )}
    </section>
  );
}

function PreferenceNode({
  item,
  isLast
}: {
  item: PreferenceTreeNode;
  isLast: boolean;
}) {
  return (
    <li className="relative pl-12">
      {/* L-shape: left edge + bottom edge forming ├ or └ */}
      <span
        aria-hidden
        className="absolute left-4 top-0 h-5 w-4 -translate-x-px rounded-bl-md border-b-2 border-l-2 border-zinc-200 dark:border-zinc-800"
      />
      {/* Vertical continuation past this row, hidden on the last child */}
      {!isLast && (
        <span
          aria-hidden
          className="absolute left-4 top-5 bottom-0 -translate-x-px border-l-2 border-zinc-200 dark:border-zinc-800"
        />
      )}
      <div
        className={[
          "flex items-start gap-3 rounded-md border bg-white px-3 py-2 dark:bg-zinc-950",
          item.matched
            ? "border-emerald-300 ring-1 ring-emerald-200 dark:border-emerald-700 dark:ring-emerald-900"
            : item.autoGenerated
              ? "border-amber-200 opacity-70 dark:border-amber-900"
              : "border-zinc-200 dark:border-zinc-800"
        ].join(" ")}
      >
        <span
          aria-label={`Rank ${item.rank}`}
          className="mt-0.5 inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-zinc-100 font-mono text-xs font-medium tabular-nums text-zinc-700 dark:bg-zinc-900 dark:text-zinc-300"
        >
          {item.rank}
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium">{item.name}</span>
            {item.role ? (
              <span
                className={`inline-block rounded px-1.5 py-0.5 text-[10px] font-medium ${ROLE_BADGE[item.role]}`}
              >
                {item.role}
              </span>
            ) : null}
          </div>
          {item.subtitle ? (
            <div className="mt-0.5 text-xs text-zinc-500">{item.subtitle}</div>
          ) : null}
          {item.badges ? (
            <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
              {item.badges}
            </div>
          ) : null}
        </div>
      </div>
    </li>
  );
}
