/**
 * Visual ranked-preference tree.
 *
 * Renders a root card at the top and one or more "branches" beneath it.
 * Each branch has a labeled title pill and a vertical list of ranked nodes
 * connected with L-shaped connectors. Pure presentational. Server-renderable.
 */

import type { Role } from "@prisma/client";
import type { ReactNode } from "react";

export interface PreferenceTreeNode {
  rank: number;
  name: string;
  role?: Role;
  subtitle?: string;
  badges?: ReactNode;
  autoGenerated?: boolean;
  matched?: boolean;
}

export interface PreferenceBranchData {
  title: string;
  caption?: string;
  emptyMessage: string;
  items: PreferenceTreeNode[];
}

interface PreferenceTreeProps {
  root: ReactNode;
  branches: PreferenceBranchData[];
}

const ROLE_BADGE: Record<Role, string> = {
  ORCH: "bg-brand-accent-soft text-brand-electric",
  POD_HEAD: "bg-sky-100 text-sky-900",
  AGENT: "bg-surface-alt text-fg-muted"
};

export function PreferenceTree({ root, branches }: PreferenceTreeProps) {
  return (
    <div>
      <div className="rounded-lg border border-border-default bg-surface px-4 py-3 shadow-sm">
        {root}
      </div>
      {branches.length > 0 && (
        <div
          aria-hidden
          className="ml-4 h-6 -translate-x-px border-l-2 border-border-default"
        />
      )}
      <div className="space-y-6">
        {branches.map((branch, i) => (
          <PreferenceBranch
            key={`${branch.title}-${i}`}
            {...branch}
            isLast={i === branches.length - 1}
          />
        ))}
      </div>
    </div>
  );
}

function PreferenceBranch({
  title,
  caption,
  emptyMessage,
  items,
  isLast
}: PreferenceBranchData & { isLast: boolean }) {
  return (
    <section className="relative">
      <div className="relative pl-8">
        <span
          aria-hidden
          className="absolute left-4 top-0 bottom-0 -translate-x-px border-l-2 border-border-default"
        />
        <span className="inline-flex items-center rounded-full bg-brand-banner px-3 py-1 font-display text-xs font-semibold uppercase tracking-[0.2em] text-white">
          {title}
        </span>
        {caption ? (
          <p className="mt-1 text-xs text-fg-muted">{caption}</p>
        ) : null}
      </div>

      <div
        aria-hidden
        className="ml-4 h-4 -translate-x-px border-l-2 border-border-default"
      />

      {items.length === 0 ? (
        <div className="ml-8 rounded-md border border-dashed border-border-strong bg-surface-muted px-4 py-6 text-center text-sm text-fg-muted">
          {emptyMessage}
        </div>
      ) : (
        <ol className="space-y-2">
          {items.map((item, idx) => (
            <PreferenceNode
              key={`${item.rank}-${item.name}`}
              item={item}
              isLast={idx === items.length - 1}
            />
          ))}
        </ol>
      )}

      {!isLast && (
        <div
          aria-hidden
          className="ml-4 mt-2 h-6 -translate-x-px border-l-2 border-border-default"
        />
      )}
    </section>
  );
}

function PreferenceNode({
  item,
  isLast
}: {
  item: PreferenceTreeNode;
  isLast: boolean;
}) {
  return (
    <li className="relative pl-12">
      <span
        aria-hidden
        className="absolute left-4 top-0 h-5 w-4 -translate-x-px rounded-bl-md border-b-2 border-l-2 border-border-default"
      />
      {!isLast && (
        <span
          aria-hidden
          className="absolute left-4 top-5 bottom-0 -translate-x-px border-l-2 border-border-default"
        />
      )}
      <div
        className={[
          "flex items-start gap-3 rounded-lg border bg-surface px-3 py-2 transition",
          item.matched
            ? "border-emerald-300 ring-1 ring-emerald-200"
            : item.autoGenerated
              ? "border-amber-200 opacity-70"
              : "border-border-default"
        ].join(" ")}
      >
        <span
          aria-label={`Rank ${item.rank}`}
          className="mt-0.5 inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand-accent-soft font-display text-xs font-semibold tabular-nums text-brand-electric"
        >
          {item.rank}
        </span>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium text-fg">{item.name}</span>
            {item.role ? (
              <span
                className={`inline-block rounded px-1.5 py-0.5 text-[10px] font-medium ${ROLE_BADGE[item.role]}`}
              >
                {item.role}
              </span>
            ) : null}
          </div>
          {item.subtitle ? (
            <div className="mt-0.5 text-xs text-fg-muted">{item.subtitle}</div>
          ) : null}
          {item.badges ? (
            <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
              {item.badges}
            </div>
          ) : null}
        </div>
      </div>
    </li>
  );
}
