"use server";

import { revalidatePath } from "next/cache";

import type { Prisma } from "@prisma/client";

import { logAudit } from "@/lib/audit";
import { getConfig } from "@/lib/config";
import { db } from "@/lib/db";
import {
  planAgentSync,
  type ExistingAgent,
  type PodHeadDirEntry
} from "@/lib/agent-sync";
import {
  fetchSheetRows,
  GoogleSheetsConfigError
} from "@/lib/google-sheets";
import { ForbiddenError, requireAdmin } from "@/lib/permissions";

import type { AgentSyncState } from "./types";

/**
 * Sync is allowed during REGISTRATION (bootstrap) or PREFERENCES (top-up).
 * Closed phases (MATCHING / RESULTS_PUBLISHED) reject — we don't want admin
 * tooling re-writing rankings after the engine has consumed them.
 */
async function assertSyncPhaseOpen(): Promise<void> {
  const phases = await db.eventPhase.findMany({
    where: { name: { in: ["REGISTRATION", "PREFERENCES"] } }
  });
  const open = phases.some((p) => p.status === "OPEN");
  if (!open) {
    throw new ForbiddenError(
      "Agent sync requires REGISTRATION or PREFERENCES to be OPEN."
    );
  }
}

async function loadPlanInputs(): Promise<{
  rows: string[][];
  podHeads: PodHeadDirEntry[];
  existing: ExistingAgent[];
  topN: number;
  allowedEmailDomains: string[];
  sheetSpec: string;
}> {
  const config = await getConfig();
  if (!config.agentSyncSheetId) {
    throw new GoogleSheetsConfigError(
      "agentSyncSheetId is not configured. Set it in /admin/config."
    );
  }

  const [rows, podHeadRows, existingRows] = await Promise.all([
    fetchSheetRows(config.agentSyncSheetId),
    db.podHeadProfile.findMany({
      include: { user: { select: { name: true, email: true, empId: true } } }
    }),
    db.user.findMany({
      select: {
        email: true,
        role: true,
        preferencesSubmittedAt: true,
        agentProfile: {
          select: {
            podHeadRankings: {
              where: { autoGenerated: false },
              select: { id: true },
              take: 1
            }
          }
        }
      }
    })
  ]);

  const podHeads: PodHeadDirEntry[] = podHeadRows.map((ph) => ({
    podHeadProfileId: ph.id,
    name: ph.user.name,
    email: ph.user.email,
    empId: ph.user.empId
  }));

  const existing: ExistingAgent[] = existingRows.map((u) => ({
    email: u.email.toLowerCase(),
    role: u.role,
    preferencesSubmitted: u.preferencesSubmittedAt !== null,
    hasManualRankings:
      (u.agentProfile?.podHeadRankings?.length ?? 0) > 0
  }));

  return {
    rows,
    podHeads,
    existing,
    topN: config.agentRanksTopNPodHeads,
    allowedEmailDomains: config.allowedEmailDomains,
    sheetSpec: config.agentSyncSheetId
  };
}

function errorState(message: string): AgentSyncState {
  return { status: "error", message };
}

export async function previewAgentSync(): Promise<AgentSyncState> {
  const admin = await requireAdmin();
  try {
    await assertSyncPhaseOpen();
    const input = await loadPlanInputs();
    const plan = planAgentSync({
      rows: input.rows,
      topN: input.topN,
      allowedEmailDomains: input.allowedEmailDomains,
      podHeads: input.podHeads,
      existingAgents: input.existing
    });

    await logAudit({
      actorId: admin.id,
      action: "AGENT_SYNC_PREVIEW",
      details: {
        sheetSpec: input.sheetSpec,
        ...plan.summary
      } satisfies Prisma.InputJsonValue
    });

    return { status: "previewed", plan, sheetSpec: input.sheetSpec };
  } catch (err) {
    return errorState(toMessage(err));
  }
}

export async function applyAgentSync(): Promise<AgentSyncState> {
  const admin = await requireAdmin();
  try {
    await assertSyncPhaseOpen();
    const input = await loadPlanInputs();
    const plan = planAgentSync({
      rows: input.rows,
      topN: input.topN,
      allowedEmailDomains: input.allowedEmailDomains,
      podHeads: input.podHeads,
      existingAgents: input.existing
    });

    const failedRowIndexes: number[] = [];
    let created = 0;
    let updated = 0;
    let skipped = plan.summary.skips;

    for (const outcome of plan.outcomes) {
      if (outcome.kind === "skip") continue;

      try {
        await db.$transaction(async (tx) => {
          // Name is derived from the email local-part. Apply on create only;
          // never overwrite a user's display name on update (they may have
          // edited it via profile setup).
          const user = await tx.user.upsert({
            where: { email: outcome.email },
            create: {
              email: outcome.email,
              name: outcome.name,
              role: "AGENT",
              syncIssues: outcome.flags
            },
            update: {
              // Reset every apply so stale flags clear when the sheet is fixed.
              syncIssues: outcome.flags
            }
          });

          const profile = await tx.agentProfile.upsert({
            where: { userId: user.id },
            create: {
              userId: user.id,
              pitch: outcome.pitch,
              skills: [],
              preferredDomains: outcome.preferredDomains
            },
            update: {
              pitch: outcome.pitch,
              preferredDomains: outcome.preferredDomains
            }
          });

          // Wipe-and-replace rankings within the same tx. Safe because all
          // existing rows for this agent are autoGenerated=true (the planner
          // already filtered out agents with manual edits).
          await tx.agentPodHeadRanking.deleteMany({
            where: { agentId: profile.id }
          });
          await tx.agentPodHeadRanking.createMany({
            data: outcome.rankings.map((podHeadId, i) => ({
              agentId: profile.id,
              podHeadId,
              rank: i + 1,
              autoGenerated: true
            }))
          });
        });

        if (outcome.kind === "create") created++;
        else updated++;
      } catch (err) {
        failedRowIndexes.push(outcome.rowIndex);
        skipped++;
        console.error(
          `[agent-sync] row ${outcome.rowIndex} (${outcome.email}) failed:`,
          err
        );
      }
    }

    await logAudit({
      actorId: admin.id,
      action: "AGENT_SYNC_APPLY",
      details: {
        sheetSpec: input.sheetSpec,
        rowsTotal: plan.summary.rowsTotal,
        created,
        updated,
        skipped,
        duplicates: plan.summary.duplicates,
        failedRowIndexes
      } satisfies Prisma.InputJsonValue
    });

    revalidatePath("/admin/agent-sync");
    revalidatePath("/admin/users");

    return {
      status: "applied",
      plan,
      applied: { created, updated, skipped, failedRowIndexes },
      sheetSpec: input.sheetSpec
    };
  } catch (err) {
    return errorState(toMessage(err));
  }
}

function toMessage(err: unknown): string {
  if (err instanceof ForbiddenError) return err.message;
  if (err instanceof GoogleSheetsConfigError) return err.message;
  if (err instanceof Error) return err.message;
  return "Unknown error";
}
